### ISSUE TITLE
信号量在这里有什么作用？

### ISSUE THREAD

**Issue by baxiang** [zixun/ANREye#1]
override func main() {
        
        while self.isCancelled == false {
            self.isMainThreadBlock = true
            DispatchQueue.main.async {
                self.isMainThreadBlock = false
                self.semaphore.signal()
            }
            
            Thread.sleep(forTimeInterval: self.threshold)
            if self.isMainThreadBlock  {
                self.handler?()
            }
            
            self.semaphore.wait(timeout: DispatchTime.distantFuture)
        }
按照我自己的代码思维： 当前变量isMainThreadBlock = YES, 让当前线程休眠0.4秒，看主线程是否修改了当前的变量isMainThreadBlock 值是否函数回调。但是我看不明白这个信号量在这个中所要做的事情是什么？

**Comment by zixun** [comment]
用来控制ping主线程的，你debug下就明白了。或者看《iOS监控编程》中卡顿监控篇
