### ISSUE TITLE
您好，有一个细节问题需要请教

### ISSUE THREAD

**Issue by allen8300** [zixun/ANREye#2]
场景：
假如现在我有个图片App，每张图片都用SDWebImage来获取；

那么，我怎么知道究竟是哪个“子线程”有异常呢？

**Comment by zixun** [comment]
首先，这个目前还不能区分。因为只要卡顿，肯定是主线程卡顿了，你这个场景是子线程把资源都吃光了，导致主线程分配不到资源而卡顿，目前在监控到卡顿的时候会把所有线程的堆栈都提取出来。但是具体是哪个线程卡顿需要自己分析。不过理论上你这个场景也是可以区分的，只要后续把CPU使用率也加入到线程中即可。CPU使用率最大的线程造成卡顿的概率也最高。
