### ISSUE TITLE
您好，PLC收集到卡顿的Thread堆栈信息后，怎么分析？

### ISSUE THREAD

**Issue by allen8300** [zixun/ANREye#3]
我已经用plcrashreporter记录了可疑的thread的堆栈信息；
但没能从中分析出来有价值的信息，您有好的分析堆栈信息的文章推荐吗？
比如下面是我抓取的某可疑线程：
![screen shot 2017-11-02 at 4 59 45 pm](https://user-images.githubusercontent.com/1751906/32319487-b8dde67a-bff5-11e7-928b-b6ac6661f011.png)

**Comment by zixun** [comment]
问题不在堆栈分析上，你的堆栈已经展示的很完善了。至于卡顿需要具体场景具体分析。能多提一点的是你这个应该是主线程，如果觉得不是主线程的卡顿，可以看看其他线程的堆栈
